repos:
  - repo: local
    hooks:
      - id: tinybird-format
        name: Tinybird Format
        entry: bash -c 'for file in "$@"; do echo "Formatting $file"; uv run tb fmt "$file" --yes; done'
        language: system
        files: ^(?!lib/).*\.(pipe|datasource|incl)$
        pass_filenames: true
        stages: [commit]

      - id: tinybird-check
        name: Tinybird Check
        entry: bash -c 'for file in "$@"; do echo "Checking $file"; if ! uv run tb check "$file"; then echo "Tinybird check failed on $file"; exit 1; fi; done'
        language: system
        files: ^(?!lib/).*\.(pipe|datasource|incl)$
        pass_filenames: true
        stages: [commit]