repos:
  - repo: local
    hooks:
      - id: tinybird-format
        name: Tinybird Format
        entry: ./tb-fmt.sh
        language: system
        always_run: true
        pass_filenames: false

      - id: tinybird-check
        name: Tinybird Check
        entry: ./tb-check.sh
        language: system
        always_run: true
        pass_filenames: false